#!/bin/bash

# Install the base system
pacstrap /mnt base base-devel

# Generate an fstab file
genfstab -U /mnt >> /mnt/etc/fstab

# Chroot into the newly installed system
arch-chroot /mnt <<EOF

# Set the hostname
echo "myhostname" > /etc/hostname

# Set the timezone
ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime

# Set the locale
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf

# Set the network configuration
echo "127.0.0.1 localhost" > /etc/hosts
echo "::1 localhost" >> /etc/hosts
echo "127.0.1.1 myhostname.localdomain myhostname" >> /etc/hosts
systemctl enable dhcpcd.service

# Install additional packages
pacman -S --noconfirm vim

# Retrieve the name of the installation disk
INSTALL_DISK=$(lsblk -dpno NAME $(mount | awk '$3 == "/" {print $1}') | head -n1)

# List available disks and retrieve the names of all disks except the installation disk
ALL_DISKS=$(lsblk -dpno NAME | grep -v "^${INSTALL_DISK}$")

# Partition and format all disks except the installation disk
for DISK in $ALL_DISKS
do
  parted -s /dev/$DISK mklabel gpt
  parted -s /dev/$DISK mkpart primary btrfs 0% 100%
  mkfs.btrfs /dev/${DISK}1
done

# Mount all BTRFS partitions
mkdir /mnt/btrfs
mount -t btrfs $(lsblk -dpno NAME | grep -v "^${INSTALL_DISK}$" | awk '{print "/dev/"$1"1"}') /mnt/btrfs

